url: http://decoupledCMS.org
title: Decoupling Content Management
description: The concept of the decoupled CMS envisions a clean separation in web editing UIs, web frameworks and content repositories
language: en-US

permalink: /news/:year-:month-:day-:title.html

future: false

sitemap: ["/index.html"]

exclude: ["README.md", "vendor"]
